### ISSUE TITLE
Map View

### ISSUE THREAD

**Issue by Alvin-idMaster** [Alvin-idMaster/672-Alvin_Anastasios#5]
This will be shown via a simple array of buttons which will show coloured maps when active.

**Comment by Alvin-idMaster** [comment]
This is a test, just to see if the automated email is disabled.

**Comment by anastasiosioannou** [comment]
manage to connect function to the button !

**Comment by Alvin-idMaster** [comment]
To switch images:
1. Create button that has a function to destroy all other images.
2. Display the corresponding image to the button.

**Comment by Alvin-idMaster** [comment]
To destroy all other images:
1. Do a function to 'find' object, based on name. See this reference: http://docs.unity3d.com/ScriptReference/GameObject.Find.html
2. Destroy the object found. See this reference: http://docs.unity3d.com/ScriptReference/Object.Destroy.html
